/* Sutras editable catalogue. Extra product photos are hidden pending better replacements. */
window.SUTRAS = {
  "name": "Sutras by S³",
  "instagram": "https://www.instagram.com/sutras.official/",
  "whatsapp": [
    "260978865604",
    "260973668415"
  ],
  "currency": "ZMW",
  "imageryIsIllustrative": true,
  "products": [
    {
      "id": "orange-three-piece-set",
      "name": "Orange Three-Piece Kurta Set",
      "cardName": "Orange Kurta Set",
      "category": "Kurta sets",
      "color": "Orange & multicolour",
      "colorHex": "#e86a29",
      "image": "assets/images/orange-set-model-clean.webp",
      "imageKind": "ai-model",
      "imageAlt": "AI-generated styling preview of an adult woman wearing the orange kurta with printed bottoms and a plain orange dupatta. Fit and small details are illustrative.",
      "description": "An orange kurta with a decorative neckline and leaf motifs, paired with multicoloured printed bottoms and a matching plain orange dupatta. Three pieces: the kurta (top), bottoms and dupatta (scarf).",
      "detail": "Three pieces shown · Embellished neckline · Leaf details & patterned fabric",
      "setContents": "Kurta, printed bottoms and plain orange dupatta (3 pieces)",
      "photoNote": "This image is AI-generated styling. Fit, length, drape and small details are approximate. Please confirm actual garment details, prices and availability with Sutras before ordering.",
      "gallery": [],
      "price": null,
      "isPreview": false
    },
    {
      "id": "pink-three-piece-set",
      "name": "Pink Three-Piece Kurta Set",
      "cardName": "Pink Kurta Set",
      "category": "Kurta sets",
      "color": "Fuchsia pink",
      "colorHex": "#d63377",
      "image": "assets/images/pink-set-model.webp",
      "imageKind": "ai-model",
      "imageAlt": "AI-generated styling preview of an adult woman wearing a fuchsia pink kurta with small gold motifs, matching pink bottoms and a tasseled dupatta. Fit and small details are illustrative.",
      "description": "A vivid pink kurta with fine front pleats, scattered gold motifs and a gold-trimmed neckline and cuffs. Paired with matching pink bottoms and a tasseled dupatta — the scarf that completes this three-piece set.",
      "detail": "Three pieces shown · Fine front pleats · Gold accents · Tasseled dupatta",
      "setContents": "Kurta, matching pink bottoms and tasseled dupatta (3 pieces)",
      "photoNote": "This image is AI-generated styling. Fit, length, drape and small details are approximate. Please confirm actual garment details, prices and availability with Sutras before ordering.",
      "gallery": [],
      "price": null,
      "isPreview": false
    },
    {
      "id": "navy-two-piece-set",
      "name": "Navy Two-Piece Kurta Set",
      "cardName": "Navy Kurta Set",
      "category": "Kurta sets",
      "color": "Navy & ivory",
      "colorHex": "#354b61",
      "image": "assets/images/navy-set-model.webp",
      "imageKind": "ai-model",
      "imageAlt": "AI-generated styling preview of an adult woman wearing a navy and ivory printed kurta with matching trousers, without a scarf. Fit and small details are illustrative.",
      "description": "Small ivory motifs and larger paisley details on a navy ground, finished with fine contrast piping and pleat details. Matching printed bottoms complete this two-piece set. No scarf or dupatta is included.",
      "detail": "Two pieces: kurta + bottoms · Floral & paisley print · No scarf / dupatta",
      "setContents": "Kurta and matching printed bottoms only (2 pieces; no scarf/dupatta)",
      "photoNote": "This image is AI-generated styling. Fit, length, drape and small details are approximate. Please confirm actual garment details, prices and availability with Sutras before ordering.",
      "gallery": [],
      "price": null,
      "isPreview": false
    },
    {
      "id": "green-two-piece-set",
      "name": "Green Two-Piece Kurta Set",
      "cardName": "Green Kurta Set",
      "category": "Kurta sets",
      "color": "Olive green",
      "colorHex": "#a5af70",
      "image": "assets/images/green-set-model.webp",
      "imageKind": "ai-model",
      "imageAlt": "AI-generated styling preview of an adult woman wearing an olive-green kurta with a red floral neckline panel and coordinating plain green trousers, without a scarf. Fit and small details are illustrative.",
      "description": "An olive-green kurta with delicate red floral detail on its framed neckline panel and subtle dark cuff trim. Coordinating plain green bottoms complete the two-piece outfit. No scarf or dupatta is included.",
      "detail": "Two pieces: kurta + bottoms · Floral yoke detail · No scarf / dupatta",
      "setContents": "Kurta and coordinating plain green bottoms only (2 pieces; no scarf/dupatta)",
      "photoNote": "This image is AI-generated styling. Fit, length, drape and small details are approximate. Please confirm actual garment details, prices and availability with Sutras before ordering.",
      "gallery": [],
      "price": null,
      "isPreview": false
    },
    {
      "id": "white-floral-two-piece-set",
      "name": "White Floral Two-Piece Set",
      "cardName": "White Floral Set",
      "category": "Co-ord sets",
      "color": "White, grey & teal",
      "colorHex": "#e4e3de",
      "description": "A white collared button-front shirt with an asymmetric floral panel and printed cuffs, paired with coordinating floral-hem trousers. Two pieces only: shirt and bottoms, with no scarf or dupatta.",
      "detail": "Two pieces: shirt + trousers · Floral panels · No scarf / dupatta",
      "setContents": "Button-front shirt and coordinating floral-hem trousers (2 pieces; no scarf/dupatta)",
      "imageAlt": "AI-generated styling preview of an adult woman in a white floral-panel collared shirt and matching floral-hem trousers, without a scarf. Fit and details are illustrative.",
      "photoNote": "This image is AI-generated styling. Fit, length, drape and small details are approximate. Please confirm actual garment details, prices and availability with Sutras before ordering.",
      "image": "assets/images/white-floral-set-model.webp",
      "imageKind": "ai-model",
      "price": null,
      "isPreview": false,
      "gallery": []
    },
    {
      "id": "yellow-floral-kurti",
      "name": "Yellow Short Kurti — Top Only",
      "cardName": "Yellow Kurti (Top Only)",
      "category": "Kurtas",
      "color": "Mustard yellow & white",
      "colorHex": "#b9a620",
      "description": "A short, hip/upper-thigh-length mustard-yellow kurti with white floral and paisley neckline detail, scattered motifs and decorated cuffs. This listing is for the kurti only. The model’s ivory trousers are styling only and are not included.",
      "detail": "Short kurti only · White floral detail · No bottoms or scarf included",
      "setContents": "Short yellow kurti only (1 piece); model styling trousers, footwear and scarf are not included",
      "imageAlt": "AI-generated styling preview of an adult woman wearing a short yellow floral kurti ending at the hips/upper thighs. The ivory trousers are styling only and are not included.",
      "photoNote": "This is a short, top-only kurti. The model’s trousers and footwear are styling props, not included merchandise. This image is AI-generated styling; exact fit and garment details should be confirmed with the store.",
      "image": "assets/images/yellow-kurti-short-model.webp",
      "imageKind": "ai-model",
      "price": null,
      "isPreview": false,
      "gallery": []
    },
    {
      "id": "dark-purple-three-piece-set",
      "name": "Dark Purple Three-Piece Kurta Set",
      "cardName": "Dark Purple Kurta Set",
      "category": "Kurta sets",
      "color": "Deep purple & white",
      "colorHex": "#3c254e",
      "description": "A deep-purple kurta with intricate white neckline and cuff details, coordinated with decorated-hem trousers and a dupatta with a white leafy-vine border. Three pieces: kurta, bottoms and scarf.",
      "detail": "Three pieces · White neckline and cuff detail · Leaf-border dupatta",
      "setContents": "Dark-purple kurta, decorated-hem bottoms and leaf-border dupatta (3 pieces)",
      "imageAlt": "AI-generated styling preview of an adult woman wearing a dark-purple kurta, white-detailed trouser hems and a matching leafy-border dupatta. Fit and details are illustrative.",
      "photoNote": "This image is AI-generated styling. Fit, length, drape and small details are approximate. Please confirm actual garment details, prices and availability with Sutras before ordering.",
      "image": "assets/images/dark-purple-set-model.webp",
      "imageKind": "ai-model",
      "price": null,
      "isPreview": false,
      "gallery": []
    },
    {
      "id": "plum-purple-three-piece-set",
      "name": "Plum Purple Three-Piece Kurta Set",
      "cardName": "Plum Purple Kurta Set",
      "category": "Kurta sets",
      "color": "Plum purple & white",
      "colorHex": "#77277e",
      "description": "A plum-purple kurta with a white paisley-floral neckline and scattered small flower details. Coordinating bottoms with a narrow white trim and a small-flower dupatta complete the three-piece set.",
      "detail": "Three pieces · White paisley-floral neckline · Small-flower dupatta",
      "setContents": "Plum-purple kurta, narrow-trim bottoms and small-flower dupatta (3 pieces)",
      "imageAlt": "AI-generated styling preview of an adult woman wearing a plum-purple kurta with white paisley-floral detail, coordinating trousers and a small-flower dupatta. Fit and details are illustrative.",
      "photoNote": "This image is AI-generated styling. Fit, length, drape and small details are approximate. Please confirm actual garment details, prices and availability with Sutras before ordering.",
      "image": "assets/images/plum-purple-set-model.webp",
      "imageKind": "ai-model",
      "price": null,
      "isPreview": false,
      "gallery": []
    },
    {
      "id": "olive-lattice-short-kurti",
      "name": "Olive Lattice Short Kurti — Top Only",
      "cardName": "Olive Short Kurti",
      "color": "Olive green",
      "colorHex": "#657532",
      "description": "A short olive-green kurti with lattice-textured chest panels, small white accents and buttons, and white paisley sleeve details. Hip/upper-thigh length. Top only; the model’s ivory trousers and footwear are styling props and are not included.",
      "detail": "Short top only · Lattice-textured front · White sleeve detail",
      "category": "Kurtas",
      "image": "assets/images/olive-lattice-short-kurti-model.webp",
      "imageKind": "ai-model",
      "price": null,
      "isPreview": false,
      "imageAlt": "AI-generated styling view of an adult woman wearing the olive green short kurti at hip/upper-thigh length. The ivory trousers are styling only, not included.",
      "setContents": "Olive green short kurti only (1 piece); styling trousers and footwear are not included. No scarf included",
      "photoNote": "This is a short, top-only kurti. The model’s trousers and footwear are styling props, not included merchandise. This image is AI-generated styling; exact fit and garment details should be confirmed with the store.",
      "gallery": []
    },
    {
      "id": "slate-grey-short-kurti",
      "name": "Slate Grey Short Kurti — Top Only",
      "cardName": "Grey Short Kurti",
      "color": "Slate grey",
      "colorHex": "#495963",
      "description": "A short slate-grey kurti with dark tone-on-tone neckline detailing, tie tassels and scattered decorative motifs. Hip/upper-thigh length. Top only; the model’s ivory trousers and footwear are styling props and are not included.",
      "detail": "Short top only · Tone-on-tone detail · Neck ties",
      "category": "Kurtas",
      "image": "assets/images/slate-grey-short-kurti-model.webp",
      "imageKind": "ai-model",
      "price": null,
      "isPreview": false,
      "imageAlt": "AI-generated styling view of an adult woman wearing the slate grey short kurti at hip/upper-thigh length. The ivory trousers are styling only, not included.",
      "setContents": "Slate grey short kurti only (1 piece); styling trousers and footwear are not included. No scarf included",
      "photoNote": "This is a short, top-only kurti. The model’s trousers and footwear are styling props, not included merchandise. This image is AI-generated styling; exact fit and garment details should be confirmed with the store.",
      "gallery": []
    },
    {
      "id": "wine-floral-short-kurti",
      "name": "Wine Floral Short Kurti — Top Only",
      "cardName": "Wine Short Kurti",
      "color": "Wine purple",
      "colorHex": "#792244",
      "description": "A short wine-purple kurti with a pale floral chest motif, a notched neckline and fine coordinating cuff trim. Hip/upper-thigh length. Top only; the model’s ivory trousers and footwear are styling props and are not included.",
      "detail": "Short top only · Floral neckline detail · Fine cuff trim",
      "category": "Kurtas",
      "image": "assets/images/wine-floral-short-kurti-model.webp",
      "imageKind": "ai-model",
      "price": null,
      "isPreview": false,
      "imageAlt": "AI-generated styling view of an adult woman wearing the wine purple short kurti at hip/upper-thigh length. The ivory trousers are styling only, not included.",
      "setContents": "Wine purple short kurti only (1 piece); styling trousers and footwear are not included. No scarf included",
      "photoNote": "This is a short, top-only kurti. The model’s trousers and footwear are styling props, not included merchandise. This image is AI-generated styling; exact fit and garment details should be confirmed with the store.",
      "gallery": []
    },
    {
      "id": "dark-green-floral-two-piece-set",
      "name": "Dark Green Floral Two-Piece Kurta Set",
      "cardName": "Dark Green Floral Set",
      "category": "Kurta sets",
      "color": "Deep green & floral",
      "colorHex": "#164b4c",
      "image": "assets/images/dark-green-floral-set-model.webp",
      "imageKind": "ai-model",
      "imageAlt": "AI-generated styling view of an adult woman in a long dark-green button-front floral kurta and matching plain trousers, without a scarf. Fit and details are illustrative.",
      "description": "A longer dark-green button-front kurta with fine chest pleats and pink-and-yellow floral panels, paired with coordinating plain trousers. Shown as a two-piece outfit: kurta and bottoms, with no scarf pictured. Please confirm availability and final garment details when ordering.",
      "detail": "Long kurta + plain trousers · Floral panels · No scarf shown",
      "setContents": "Long floral kurta and coordinating plain trousers (2 pieces as photographed; no scarf shown)",
      "photoNote": "This image is AI-generated styling. Fit, length, drape and small details are approximate. Please confirm actual garment details, prices and availability with Sutras before ordering.",
      "gallery": [],
      "price": null,
      "isPreview": false
    }
  ]
};
